"""Reading and checking a stream manifest.

The Python half. `interface/manifest.js` is the same thing in the other
language, and `fixtures/streams.json` is what stops the two drifting: it is
generated by running these functions, and both suites read it, so a rule
expressed in one language and forgotten in the other fails in the other.

See CONTRACT.md. Where this file and the contract disagree, the contract is
right and this is a bug.
"""

import json
import re
import os

CONTRACT = "1.0"

# The seven, in the order a board draws them. Nothing may add an eighth without
# changing the contract, which is the point of naming them in one place: an
# agent that wants its own state wants `owner` instead.
#
# `accepted` arrived on 12 Sep 2026, the one addition the contract has taken.
# It is the gap between a person approving an item and the work it describes
# being finished — a plan he has agreed sits there while the run it minted is
# still going. That gap was `done` until now, which made "I have accepted this"
# and "this is finished" one state, and they are two different answers.
CANONICAL = ("backlog", "ready", "doing", "blocked", "review", "accepted", "done")

# Which of the six mean "a person has to look at this". The one question every
# reader asks and no stream should answer differently.
WAITING_ON_A_PERSON = ("review",)

CONTAINERS = ("list-file", "doc-folder")
WRITERS = ("http-put", "subprocess", "queue-file")
# How much of an agent's work waits on a person. See "Handover level" in
# CONTRACT.md.
HANDOVER_LEVELS = ("off", "plan-first", "just-do-it")

SKIP_DIRS = {"node_modules", ".git", "EXTERNAL", "TEMP", "__pycache__", "dist", "build"}
MAX_DEPTH = 3


def discover(root):
    """Every folder under `root` holding a stream.json, three levels down.

    Same depth and the same skip list as the agents dashboard uses for
    agent.json, deliberately: a folder can hold both files, because an agent
    that owns a queue is an agent and a stream, and the two answer different
    questions about it.
    """
    found = []
    root = os.path.abspath(root)
    for here, dirs, files in os.walk(root):
        depth = here[len(root):].count(os.sep)
        if depth >= MAX_DEPTH:
            dirs[:] = []
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]
        if "stream.json" in files:
            found.append(os.path.join(here, "stream.json"))
    return sorted(found)


def load(path):
    """Read one manifest. Returns (manifest, errors); a broken one is not an
    exception, because one unreadable stream must not take the page with it."""
    try:
        with open(path, encoding="utf-8") as fh:
            m = json.load(fh)
    except Exception as err:                       # noqa: BLE001 - reported, not raised
        return None, ["could not read %s: %s" % (path, err)]
    if not isinstance(m, dict):
        return None, ["%s is not a JSON object" % path]
    m.setdefault("_path", path)
    m.setdefault("_root", os.path.dirname(path))
    return m, validate(m)


def validate(m):
    """Everything wrong with a manifest, as lines meant to be read by a person.

    Values are quoted with json.dumps rather than %r. The messages have to come
    out byte for byte the same as interface/manifest.js's, because both are
    pinned by the one fixture, and %r quotes with apostrophes where
    JSON.stringify quotes with speech marks.

    Reported rather than raised, and all of them rather than the first, because
    the caller is usually someone who has just written the file and would
    otherwise fix one typo per run.
    """
    e = []
    if m.get("contract") != CONTRACT:
        e.append("contract should be %s, found %s" % (json.dumps(CONTRACT), json.dumps(m.get("contract"))))
    for key in ("id", "name", "container", "states", "writer"):
        if not m.get(key):
            e.append("missing %s" % json.dumps(key))

    c = m.get("container") or {}
    if c and c.get("kind") not in CONTAINERS:
        e.append("container.kind should be one of %s, found %s" % (", ".join(CONTAINERS), json.dumps(c.get("kind"))))
    if c and not c.get("path"):
        e.append("container.path is missing")

    states = m.get("states") or {}
    for k in states:
        if k not in CANONICAL:
            e.append("%s is not one of the seven states (%s)" % (json.dumps(k), ", ".join(CANONICAL)))
    labels = [v for v in states.values()]
    if len(labels) != len(set(labels)):
        e.append("two states share a label, so one cannot be told from the other")
    if states and "done" not in states:
        e.append("no label for 'done'; every stream needs somewhere finished work goes")

    w = m.get("writer") or {}
    how = w.get("how") or {}
    if w and not w.get("who"):
        e.append("writer.who is missing")
    if w and how.get("kind") not in WRITERS:
        e.append("writer.how.kind should be one of %s, found %s" % (", ".join(WRITERS), json.dumps(how.get("kind"))))
    if how.get("kind") == "subprocess" and not how.get("apply"):
        e.append("a subprocess writer needs an 'apply' command")
    if how.get("kind") == "http-put" and not how.get("path"):
        e.append("an http-put writer needs a path")

    # A lane a stream reserves but never names is a rename nothing defends.
    for r in m.get("reserved") or []:
        if r not in labels and r not in [s.get("lane") for s in m.get("synthetic") or []]:
            e.append("reserved lane %s is not a state label or a synthetic lane" % json.dumps(r))

    for s in m.get("synthetic") or []:
        if not s.get("lane"):
            e.append("a synthetic lane has no name")
        if s.get("before") and s["before"] not in CANONICAL:
            e.append("synthetic lane %s sits before %s, which is not a state" % (json.dumps(s.get("lane")), json.dumps(s["before"])))
    return e


def label(m, state):
    """The stream's own word for a canonical state."""
    return (m.get("states") or {}).get(state) or state


def canonical(m, word):
    """The canonical state behind one of the stream's words, or None.

    Case and surrounding space are ignored, because these come off headings
    somebody typed.
    """
    if not word:
        return None
    want = " ".join(str(word).split()).lower()
    for state, lab in (m.get("states") or {}).items():
        if " ".join(str(lab).split()).lower() == want:
            return state
    return None


def lanes(m):
    """Every lane a board draws, in order, real and synthetic together.

    A synthetic lane is placed by the state it sits before, so a stream says
    where its extra column goes rather than the board knowing. A synthetic lane
    naming a state the stream does not use falls to the end rather than being
    dropped, because a column nobody can see is worse than one in the wrong
    place.
    """
    order = [s for s in CANONICAL if s in (m.get("states") or {})]
    out = []
    syn = m.get("synthetic") or []
    for state in order:
        for s in syn:
            if s.get("before") == state:
                out.append({"lane": s.get("lane"), "state": s.get("state"), "synthetic": True,
                            "draggable": bool(s.get("draggable")), "when": s.get("when"),
                            "hint": (m.get("hints") or {}).get(s.get("lane"), "")})
        lab = label(m, state)
        # A synthetic lane may stand in for a real state, the way Done does:
        # ticked in place, with no heading of its own anywhere in the file.
        stands_in = next((s for s in syn if s.get("state") == state), None)
        if stands_in:
            out.append({"lane": stands_in.get("lane"), "state": state, "synthetic": True,
                        "draggable": bool(stands_in.get("draggable")), "when": stands_in.get("when"),
                        "hint": (m.get("hints") or {}).get(stands_in.get("lane"), "")})
            continue
        out.append({"lane": lab, "state": state, "synthetic": False, "draggable": True,
                    "when": None, "hint": (m.get("hints") or {}).get(lab, "")})
    for s in syn:
        if s.get("before") in (m.get("states") or {}) or s.get("state") in (m.get("states") or {}):
            continue
        if any(o["lane"] == s.get("lane") for o in out):
            continue
        out.append({"lane": s.get("lane"), "state": s.get("state"), "synthetic": True,
                    "draggable": bool(s.get("draggable")), "when": s.get("when"),
                    "hint": (m.get("hints") or {}).get(s.get("lane"), "")})
    return out


def waiting_on_a_person(m, state):
    """Whether an item in this state is the person's move rather than an agent's."""
    return state in WAITING_ON_A_PERSON


def owns_its_file(m):
    """True when this stream's reader may write the file itself.

    Exactly one stream per reader may answer True. Everything else goes through
    the stream's own command, which is the whole of how one-writer-per-file is
    kept true rather than merely asked for.
    """
    return ((m.get("writer") or {}).get("how") or {}).get("kind") == "http-put"


# ---------------------------------------------------------------------------
# An item's history
#
# What happened to one item, one event a line, appended and never rewritten.
# See "An item's history" in CONTRACT.md. One kind today: a call, an owner
# bringing a specialist in. A specialist never owns an item, so the one thing
# checked beyond the shape is that `called` is never `by`.

EVENT_KINDS = ("call",)
# What a specialist brought in did: gave a view, or did part of the work.
CALL_DID = ("view", "work")
_ABOUT_RE = re.compile(r"^[a-z]+:[0-9a-z]{6}$")
_AT_RE = re.compile(r"^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}(:\d{2})?)?$")


def validate_event(ev):
    """Everything wrong with one history event, as lines, in the same words as
    wsValidateEvent. A reader skips an event that has any."""
    if not isinstance(ev, dict):
        return ["not an object"]
    e = []
    for key in ("at", "about", "by", "kind"):
        if not ev.get(key):
            e.append("missing %s" % json.dumps(key))
    if ev.get("at") and not _AT_RE.match(str(ev["at"])):
        e.append("at should be an ISO date or datetime, found %s" % json.dumps(ev["at"]))
    if ev.get("about") and not _ABOUT_RE.match(str(ev["about"])):
        e.append('about should be a typed reference like "task:ab12cd", found %s' % json.dumps(ev["about"]))
    if ev.get("kind") and ev["kind"] not in EVENT_KINDS:
        e.append("kind should be one of %s, found %s" % (", ".join(EVENT_KINDS), json.dumps(ev["kind"])))
    if ev.get("kind") == "call":
        if not ev.get("called"):
            e.append("a call names nobody it called")
        elif ev.get("called") == ev.get("by"):
            e.append("an owner cannot call itself in as a specialist")
        if ev.get("did") not in CALL_DID:
            e.append("did should be one of %s, found %s" % (", ".join(CALL_DID), json.dumps(ev.get("did"))))
    if ev.get("note") is not None and len(str(ev["note"])) > 500:
        e.append("note is longer than 500 characters")
    return e
