'use strict';

/* =========================================================================
   Reading and checking a stream manifest

   The browser half. `manifest.py` beside it is the same thing in the other
   language, and `fixtures/streams.json` is what stops the two drifting: it is
   generated by running these functions, and both suites read it, so a rule
   expressed here and forgotten there fails there.

   See CONTRACT.md. Where this file and the contract disagree, the contract is
   right and this is a bug.

   A classic script, and it has to stay one. The board loads it with a plain
   script tag before its own scripts and reads these names out of the shared
   global scope, so a module would be deferred past the point where they are
   first needed. There is no window, no document and no state in here, because
   the suite runs it in a bare context with none of them.
   ========================================================================= */

const WS_CONTRACT = '1.0';

/* The seven, in the order a board draws them. Nothing may add an eighth without
   changing the contract, which is the point of naming them in one place: an
   agent that wants a state of its own wants `owner` instead.

   `accepted` arrived on 12 Sep 2026, the one addition the contract has taken.
   It is the gap between a person approving an item and the work it describes
   being finished — a plan he has agreed sits there while the run it minted is
   still going. That gap was `done` until now, which made "I have accepted
   this" and "this is finished" one state, and they are two different
   answers. */
const WS_CANONICAL = ['backlog', 'ready', 'doing', 'blocked', 'review', 'accepted', 'done'];

/* Which of the seven mean a person has to look. The one question every reader
   asks, and no stream should answer it differently. */
const WS_WAITING_ON_A_PERSON = ['review'];

const WS_CONTAINERS = ['list-file', 'doc-folder'];
const WS_WRITERS = ['http-put', 'subprocess', 'queue-file'];

/* Everything wrong with a manifest, as lines meant to be read by a person.
   Returned rather than thrown, and all of them rather than the first, because
   the reader is usually someone who has just written the file and would
   otherwise fix one typo per run. */
function wsValidate(m){
  const e = [];
  if (!m || typeof m !== 'object') return ['not an object'];
  if (m.contract !== WS_CONTRACT) e.push(`contract should be "${WS_CONTRACT}", found ${JSON.stringify(m.contract)}`);
  for (const key of ['id', 'name', 'container', 'states', 'writer'])
    if (!m[key]) e.push(`missing "${key}"`);

  const c = m.container || {};
  if (m.container && !WS_CONTAINERS.includes(c.kind))
    e.push(`container.kind should be one of ${WS_CONTAINERS.join(', ')}, found ${JSON.stringify(c.kind)}`);
  if (m.container && !c.path) e.push('container.path is missing');

  const states = m.states || {};
  for (const k of Object.keys(states))
    if (!WS_CANONICAL.includes(k)) e.push(`"${k}" is not one of the seven states (${WS_CANONICAL.join(', ')})`);
  const labels = Object.values(states);
  if (labels.length !== new Set(labels).size)
    e.push('two states share a label, so one cannot be told from the other');
  if (Object.keys(states).length && !states.done)
    e.push("no label for 'done'; every stream needs somewhere finished work goes");

  const w = m.writer || {};
  const how = w.how || {};
  if (m.writer && !w.who) e.push('writer.who is missing');
  if (m.writer && !WS_WRITERS.includes(how.kind))
    e.push(`writer.how.kind should be one of ${WS_WRITERS.join(', ')}, found ${JSON.stringify(how.kind)}`);
  if (how.kind === 'subprocess' && !how.apply) e.push("a subprocess writer needs an 'apply' command");
  if (how.kind === 'http-put' && !how.path) e.push('an http-put writer needs a path');

  // A lane a stream reserves but never names is a rename nothing defends.
  for (const r of m.reserved || [])
    if (!labels.includes(r) && !(m.synthetic || []).some(s => s.lane === r))
      e.push(`reserved lane "${r}" is not a state label or a synthetic lane`);

  for (const s of m.synthetic || []){
    if (!s.lane) e.push('a synthetic lane has no name');
    if (s.before && !WS_CANONICAL.includes(s.before))
      e.push(`synthetic lane "${s.lane}" sits before "${s.before}", which is not a state`);
  }
  return e;
}

/* The stream's own word for a canonical state. */
function wsLabel(m, state){ return (m.states || {})[state] || state; }

/* The canonical state behind one of the stream's words, or null. Case and
   surrounding space ignored, because these come off headings somebody typed. */
function wsCanonical(m, word){
  if (!word) return null;
  const want = String(word).replace(/\s+/g, ' ').trim().toLowerCase();
  for (const [state, lab] of Object.entries(m.states || {}))
    if (String(lab).replace(/\s+/g, ' ').trim().toLowerCase() === want) return state;
  return null;
}

/* Every lane a board draws, in order, real and synthetic together.

   A synthetic lane is placed by the state it sits before, so a stream says
   where its extra column goes rather than the board knowing. One naming a
   state the stream does not use falls to the end rather than being dropped: a
   column nobody can see is worse than one in the wrong place. */
function wsLanes(m){
  const states = m.states || {};
  const syn = m.synthetic || [];
  const hint = lane => (m.hints || {})[lane] || '';
  const out = [];
  for (const state of WS_CANONICAL){
    if (!(state in states)) continue;
    for (const s of syn)
      if (s.before === state)
        out.push({ lane: s.lane, state: s.state || null, synthetic: true,
                   draggable: !!s.draggable, when: s.when || null, hint: hint(s.lane) });
    /* A synthetic lane may stand in for a real state, the way Done does:
       ticked in place, with no heading of its own anywhere in the file. */
    const standsIn = syn.find(s => s.state === state);
    if (standsIn){
      out.push({ lane: standsIn.lane, state, synthetic: true,
                 draggable: !!standsIn.draggable, when: standsIn.when || null, hint: hint(standsIn.lane) });
      continue;
    }
    out.push({ lane: wsLabel(m, state), state, synthetic: false,
               draggable: true, when: null, hint: hint(wsLabel(m, state)) });
  }
  for (const s of syn){
    if (s.before in states || s.state in states) continue;
    if (out.some(o => o.lane === s.lane)) continue;
    out.push({ lane: s.lane, state: s.state || null, synthetic: true,
               draggable: !!s.draggable, when: s.when || null, hint: hint(s.lane) });
  }
  return out;
}

/* Whether an item in this state is the person's move rather than an agent's. */
function wsWaitingOnAPerson(m, state){ return WS_WAITING_ON_A_PERSON.includes(state); }

/* True when this stream's reader may write the file itself. Exactly one stream
   per reader may answer true; everything else goes through the stream's own
   command, which is the whole of how one-writer-per-file is kept true rather
   than merely asked for. */
function wsOwnsItsFile(m){ return ((m.writer || {}).how || {}).kind === 'http-put'; }
